"""student ranks

Revision ID: 339519945c05
Revises: 7eb9228f7a6a
Create Date: 2018-05-25 12:14:19.044898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339519945c05'
down_revision = '7eb9228f7a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('belt_colour', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_ranks',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('rank_id', sa.Integer(), nullable=False),
    sa.Column('date_attained', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rank_id'], ['rank.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'rank_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_ranks')
    op.drop_table('rank')
    op.drop_table('level')
    # ### end Alembic commands ###
