"""flags

Revision ID: 9fde238abf12
Revises: 339519945c05
Create Date: 2018-05-25 14:44:30.904796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fde238abf12'
down_revision = '339519945c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('rank', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rank', 'is_deleted')
    op.drop_column('level', 'is_deleted')
    # ### end Alembic commands ###
